# Generated by Django 6.0.2 on 2026-02-17 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('anio_publicacion', models.IntegerField()),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('descripcion', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('tipo', models.CharField(choices=[('novela', 'Novela'), ('cuento', 'Cuento'), ('ensayo', 'Ensayo'), ('poesia', 'Poesía'), ('biografia', 'Biografía'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('otro', 'Otro')], default='novela', max_length=20)),
                ('cantidad_total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_disponible', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('es_popular', models.BooleanField(default=False)),
                ('es_nuevo', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='core.autor')),
                ('categorias', models.ManyToManyField(related_name='libros', to='core.categoria')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='core.editorial')),
            ],
            options={
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('devolucion', 'Devolución'), ('vencimiento', 'Vencimiento'), ('reserva', 'Reserva disponible'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('max_prestamos', models.IntegerField(default=3)),
                ('dias_prestamo_default', models.IntegerField(default=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('renovado', 'Renovado')], default='activo', max_length=20)),
                ('renovaciones', models.IntegerField(default=0)),
                ('max_renovaciones', models.IntegerField(default=2)),
                ('notas', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_reserva'],
            },
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='core_libro_titulo_76fb03_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='core_libro_autor_i_e2e74e_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['-fecha_agregado'], name='core_libro_fecha_a_535d46_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['usuario', 'estado'], name='core_presta_usuario_d2ced3_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['libro', 'estado'], name='core_presta_libro_i_4e96f1_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['-fecha_prestamo'], name='core_presta_fecha_p_700de9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('libro', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['libro', 'estado'], name='core_reserv_libro_i_ddc05d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario', 'estado'], name='core_reserv_usuario_81a253_idx'),
        ),
    ]
