# Generated by Django 6.0.2 on 2026-02-20 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='libros'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='usuario'),
        ),
    ]
